### ISSUE TITLE
JQuery in dependency

### ISSUE THREAD

**Issue by mateeyow** [brownieboy/react-bootstrap-slider#32]
What's the jquery in the package.json for?

**Comment by brownieboy** [comment]
Yeah, that doesn't need to be there.  It should be a peer dependency, at best.  In fact, probably not even that.

I'll remove on the next update.

**Comment by brownieboy** [comment]
Moved bootstrap, jquery, react and react-dom from the `dependencies` section to both the `peerDependencies` _and_ `devDependencies` sections.

FYI, the bootstrap-slider component requires jQuery, but doesn't list it in its own `dependencies` or `peerDependencies` sections.

Rolled out to npmjs as version 1.1.6.

**Comment by mateeyow** [comment]
Does bootstrap-slider use jQuery by default? I've read it doesn't right?

**Comment by brownieboy** [comment]
Yep.  It's right there in the source code: https://github.com/seiyria/bootstrap-slider/blob/master/src/js/bootstrap-slider.js.

When I initially deleted jQuery entirely from the package.json of my own component, I got the following error when I ran my start script:

> ERROR in ./~/bootstrap-slider/dist/bootstrap-slider.js
> Module not found: Error: Cannot resolve module 'jquery' in /Users/michaelbrown/Documents/Development/react-bootstrap-slider/node_modules/bootstrap-slider/dist
>  @ ./~/bootstrap-slider/dist/bootstrap-slider.js 56:2-29

**Comment by brownieboy** [comment]
Hmmm... I think I need to revisit this.  Seiyria's readme _does_ say that jQuery is an optional dependency, and that bootstrap-slider will work either with it or without it.

**Comment by mateeyow** [comment]
Yeah. That was what i was wondering about.

**Comment by brownieboy** [comment]
Okay, what Seiyria's code does is _attempt_ to require jQuery, but traps the error if that fails.  This enables him to run different code, depending on whether jQuery is present or not.   So bootstrap-slider makes use of jQuery if it's present, but is still able to function if it's not.

That said, I think it's safe to completely remove jQuery as any kind of dependency for react-bootstrap-slider, so that's what I'm going to do.

**Comment by mateeyow** [comment]
Alright. Thanks for the info.

**Comment by brownieboy** [comment]
I ran into issues where the development version (`npm start`) would build if jQuery wasn't present.  This turns out to be a known upstream issue with bootstrap-slider, see https://github.com/seiyria/bootstrap-slider#how-do-i-exclude-the-optional-jquery-dependency-from-my-build

I've implemented the jQuery stub method that they've detailed here, and that's fixed the issue.

**Comment by brownieboy** [comment]
jQuery-less version just rolled out to npmjs as 1.1.7.
