### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by michael-reeves** [brownieboy/react-bootstrap-slider#34]
There appears to be some problem with 1.1.6 dependency on jquery.  I got the following error when installing.

```
Failed to compile.

Error in ./~/bootstrap-slider/dist/bootstrap-slider.js
Module not found: 'jquery' in /Users/me/myproj/node_modules/bootstrap-slider/dist

 @ ./~/bootstrap-slider/dist/bootstrap-slider.js 56:2-29
```

Manually adding jQuery to the project fixed the issue.  Although, doing that installed jquery@3.2.1 on my system.

Not sure if this is a Yarn/NPM problem or a ReactBootstrapSlider problem.

**Comment by brownieboy** [comment]
What exactly are you doing?  Are doing an `npm install react-bootstrap-slider` into an existing project or are you checking out its repository and trying to build a new version for yourself?

**Comment by michael-reeves** [comment]
I was trying to add react-bootstrap-slider to my project.  Basically following the instructions in the Readme.

`yarn add react-bootstrap-slider`

**Comment by brownieboy** [comment]
Please see #32, because I think I've just the same issue.   If so, it's an upstream issue with bootstrap-slider if you're building your project with browserify or webpack.  Please see  https://github.com/seiyria/bootstrap-slider#how-do-i-exclude-the-optional-jquery-dependency-from-my-build for ways that you can workaround this.

You can check the react-boostrap-slider webpack config file to see how I fixed it there.

**Comment by michael-reeves** [comment]
Well, you are correct.  I updated to 1.1.7, but it looks like I will have to update my webpack config.  Removing jquery from package.json caused the problem to reappear.

Since I'm using create-react-app, and I haven't exploded all the hidden stuff yet, I'm going to hold off on doing that for now.  Once I do extract all the pieces I will revisit this.

**Comment by discordianfish** [comment]
Instill get the same error.. will investigate further tomorrow. But happened to me on CI, on clean slate.
